# Generated by Django 4.1.6 on 2023-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theatre", "0002_alter_seats_column_alter_seats_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies", name="duration", field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="movies",
            name="language",
            field=models.CharField(
                choices=[("Hin", "Hindi"), ("Eng", "English"), ("Kan", "Kannada")],
                max_length=20,
            ),
        ),
    ]
