# Generated by Django 4.1.6 on 2023-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theatre", "0004_alter_show_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="cost",
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
