# Generated by Django 4.1.6 on 2023-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theatre", "0005_show_cost"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="halls",
            constraint=models.UniqueConstraint(
                fields=("name", "theatre"), name="unique_hall"
            ),
        ),
        migrations.AddConstraint(
            model_name="seats",
            constraint=models.UniqueConstraint(
                fields=("number", "row", "column", "hall"), name="unique_seat"
            ),
        ),
    ]
