# Generated by Django 4.1.6 on 2023-02-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Theatre", "0007_halls_user_movies_user_seats_user_show_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="halls",
            name="theatre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="Theatre.theatre",
            ),
        ),
        migrations.AlterField(
            model_name="halls",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="halls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="movies",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seats",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="Theatre.halls",
            ),
        ),
        migrations.AlterField(
            model_name="seats",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="Theatre.halls",
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="Theatre.movies",
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="theatre",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="theatres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
