# Generated by Django 4.1.6 on 2023-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theatre", "0005_show_cost"),
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="res_seats",
            field=models.ManyToManyField(
                related_name="seat_book",
                through="ticket.seat_reserved",
                to="Theatre.seats",
            ),
        ),
    ]
