# Generated by Django 4.1.6 on 2023-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_remove_tickets_res_seats_tickets_count"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="seat_reserved",
            constraint=models.UniqueConstraint(
                fields=("seat", "show"), name="unique_reserve"
            ),
        ),
    ]
