# Generated by Django 4.1.6 on 2023-02-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0004_seat_reserved_unique_reserve"),
    ]

    operations = [
        migrations.RemoveField(model_name="tickets", name="count",),
        migrations.AddField(
            model_name="seat_reserved",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
