# Generated by Django 4.1.6 on 2023-02-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Theatre", "0008_alter_halls_theatre_alter_halls_user_and_more"),
        ("ticket", "0005_remove_tickets_count_seat_reserved_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat_reserved",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_seats",
                to="Theatre.seats",
            ),
        ),
        migrations.AlterField(
            model_name="seat_reserved",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_seats",
                to="Theatre.show",
            ),
        ),
        migrations.AlterField(
            model_name="seat_reserved",
            name="tickets",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_seats",
                to="ticket.tickets",
            ),
        ),
        migrations.AlterField(
            model_name="seat_reserved",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_seats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="Theatre.show",
            ),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
